# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'globalmart'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'  # Ensure this profile name matches your ~/.dbt/profiles.yml configuration

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled SQL files will be stored after running dbt commands
target-path: "testing"  # directory which will store compiled SQL files

# Directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  globalmart:
    # Applies to all files under models/RAW/
    RAW:
      +materialized: table  # Ensure raw data is materialized as a table
